version: "2.0"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24225:24224"
      - "24225:24224/udp"
  web:
    image: httpd
    ports:
      - "8080:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24225
        tag: flnginx
# Needed to work in Cyfronet
networks:
#  default:
#    driver: bridge
#    driver_opts:
#      com.docker.network.driver.mtu: 1400
